name: fluent_validation
description: Validação de classes inspirado no Fluent Validation do C#
version: 2.0.0
homepage: https://github.com/bernardoveras/Dart-Fluent-Validation

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.9
